










const addPlayerButton = document.getElementById("addPlayerButton");

const inputContainer = document.getElementById("inputContainer");

const playerNameInput = document.getElementById("playerName");

const addToTeamButton = document.getElementById("addToTeamButton");

const playButton = document.getElementById("playButton");

const refreshButton = document.getElementById("refreshButton");

const truthButton = document.getElementById("truthButton");

const dareButton = document.getElementById("dareButton");

const resultContainer = document.getElementById("result");



const playerArray = [];

let selectedPlayerIndex = null;

let truthMessage = "";

let dareMessage = "";

let selectedPlayerName = "";



addPlayerButton.addEventListener("click", () => {

  inputContainer.style.display = "block";

  updateResult();

});



addToTeamButton.addEventListener("click", () => {

  const playerName = playerNameInput.value;

  if (playerName) {

    playerArray.push(playerName);

    playerNameInput.value = "";

    updateResult();

  }

});

let lastTwoPlayerTruth = false;


playButton.addEventListener("click", () => {
  if (playerArray.length > 0) {
    selectedPlayerIndex = Math.floor(Math.random() * playerArray.length);
    selectedPlayerName = playerArray[selectedPlayerIndex];

    truthMessage = getRandomTruth();
    dareMessage = getRandomDare();

    // Check if either truth or dare message is available
    if (truthMessage || dareMessage) {
      refreshButton.style.display = "block";
      truthButton.style.display = "block";
      dareButton.style.display = "block";

      // Enable truth and dare buttons if messages are available
      truthButton.disabled = !truthMessage;
      dareButton.disabled = !dareMessage;

      playButton.disabled = true; // Disable the Play button initially
      resultContainer.textContent = `Selected Player: ${selectedPlayerName}`;
    } else {
      resultContainer.textContent = "Please select Truth or Dare.";
    }
  } else {
    resultContainer.textContent = "No players added yet.";
  }
});


// Add event listeners for the Truth and Dare buttons to enable the Play button
truthButton.addEventListener("click", () => {
  playButton.disabled = false;
});

dareButton.addEventListener("click", () => {
  playButton.disabled = false;
});






truthButton.addEventListener("click", () => {

  dareButton.disabled = true;

  resultContainer.innerHTML = `

      Selected Player: ${selectedPlayerName}<br>

      Truth: ${truthMessage}

    `;

});



dareButton.addEventListener("click", () => {

  truthButton.disabled = true;

  resultContainer.innerHTML = `

      Selected Player: ${selectedPlayerName}<br>

      Dare: ${dareMessage}

    `;

});



refreshButton.addEventListener("click", () => {

  location.reload(); // Reload the page to reset the game

});



function updateResult() {

  if (playerArray.length > 0) {

    playButton.style.display = "block";

    playButton.disabled = playerArray.length <= 1;

  } else {

    playButton.style.display = "none";

    refreshButton.style.display = "none";

    truthButton.style.display = "none";

    dareButton.style.display = "none";

  }

}

function getRandomTruth() {
  const truthOptions = [
    "Give someone a piggyback ride!",
    "Do not blink for a minute!",
    "Any time someone takes a drink, ask them for a sip!",
    "Do your best Buzz Lightyear impression!",
    "Run around the outside of the house three times!",
    "Go outside and yell, “I pick my nose!” to the first person you see!",
    "Put your leg behind your head!",
    "Eat a spoonful of hot sauce!",
    "Hug your mailbox (or a tree or lawn ornament) for 20 seconds!",
    "Sing the Star-Spangled Banner in your best opera voice!",
    "Take a bite out of a stick of butter!",
    "Draw a face on your hand and talk with your hand when it’s your turn!",
    "Let the person standing closest to you do your make-up crazy. Keep it on for at least an hour!",
    "Talk with your tongue sticking out!",
    "Do the next dare for the next person that gets one!",
    "Text someone using only your nose!",
    "Use the driveway as a catwalk for 5 minutes and wave to passing people!",
    "Do jumping jacks until your next turn!",
    "Brush your teeth in front of everyone!",
    "Do 10 perfect pushups!",
    "Go up to anyone on the street and ask, “How could you?” with much emotion!",
    "Eat a spoonful of mustard!",
    "Play the air guitar!",
    "Have you ever skipped school?",
    "What do you want to do when you grow up?",
    "Would you rather go to the beach or the mountains?",
    "What is your favorite meal?",
    "Do you like romantic movies?",
    "Which superhero do you dig the most?",
    "What is your nickname?",
    "What is the least favorite gift you’ve ever received?",
    "What would you do if you were a giant?",
    "Do you like hot dogs?",
    
  "What's the most embarrassing thing that's happened to you in school?",
  "Who is your celebrity crush?",
  "What's the most daring thing you've done with your friends?",
  "Have you ever had a secret crush on someone in this group?",
  "What's the silliest rumor you've heard about yourself?",
  "What's your favorite subject in school and why?",
  "Have you ever stayed up all night texting or chatting with someone?",
  "What's the most memorable dream you've had recently?",
  "What's something you're really good at that not many people know about?",
  "Have you ever snuck out of the house at night?",
  "What's the last thing you searched for on the internet?",
  "If you could switch lives with anyone for a day, who would it be and why?",
  "What's your biggest fear?",
  "Have you ever had a crush on a teacher?",
  "What's the most trouble you've ever been in with your parents?",
  "If you could have any superpower, what would it be and how would you use it?",
  "What's the most embarrassing thing your parents have caught you doing?",
  "Do you have a secret talent? If so, what is it?",
  "What's your favorite social media platform, and what do you like to post about?",
  "What's the last lie you told and why?",
  "Have you ever had a crush on someone your best friend liked?",
  "What's the most important quality you look for in a friend?",
  "What's your go-to karaoke song?",
  "Have you ever borrowed something from a friend and not returned it?",
  "If you could travel anywhere in the world, where would you go and why?",
  "What's the most embarrassing app on your phone?",
  "What's the most ridiculous outfit you've ever worn?",
  "What's a weird food combination that you enjoy?",
  "Have you ever prank-called someone?",
  "What's something you wish you were better at?",
  "Have you ever had a crush on someone you met online?",
  "What's the most awkward situation you've been in with your crush?",
  "If you could relive one day from your childhood, which day would it be?",
  "What's your favorite way to relax after a stressful day?",
  "Have you ever broken a rule at school and not gotten caught?",
  "What's the most embarrassing text message you've sent to the wrong person?",
  "If you could switch lives with someone in your family for a day, who would it be and why?",
  "What's the most rebellious thing you've done?",
  "What's a hobby or interest you'd like to explore more?",
  "Have you ever had a crush on someone significantly older or younger than you?",
  "What's the most embarrassing thing you've done in front of your crush?",
  "Have you ever pretended to be sick to get out of something?",
  "What's the most spontaneous thing you've ever done?",
  "Have you ever had a crush on a fictional character?",
  "What's the most adventurous thing you'd like to try?",
  "Have you ever cheated on a test?",
  "What's a hidden talent you have that no one knows about?",
  "Have you ever regretted sending a text or social media post?",
  "What's the most embarrassing fashion trend you've followed?",
  "If you could be any character from a book or movie, who would you choose and why?",
  "What's the weirdest dream you've ever had?",
  "Have you ever had a crush on someone you met at a summer camp or vacation?",
  "What's a goal you're currently working towards?",
  "Have you ever been caught in a lie by your parents?",
  "What's your favorite way to procrastinate?",
  "Have you ever tried a dare from a social media challenge?",
  "What's something you'd like to change about your school?",
  "Have you ever had a disagreement with a teacher?",
  "What's the most embarrassing thing you've posted on social media?",
  "Have you ever had a pet that you kept a secret from your parents?",
  "What's the most unusual pet you'd like to have?",
  "Have you ever pretended to like a certain type of music to fit in?",
  "What's the most embarrassing nickname you've been given?",
  "Have you ever had a crush on someone you met at a family event?",
  "What's a food you dislike that most people seem to enjoy?",
  "Have you ever accidentally sent a text to the wrong person?",
  "What's your favorite childhood memory?",
  "Have you ever eavesdropped on a conversation?",
  "What's the most creative excuse you've come up with to get out of something?",
  "Have you ever been grounded? What was it for?",
  "What's the most daring fashion choice you've made?",
  "Have you ever been on a blind date or set someone up on one?",
  "What's a TV show or movie you're embarrassed to admit you enjoy?",
  "Have you ever had a crush on someone you met at a family event?",
  "What's a skill you wish you were better at?",
  "Have you ever kept a journal or diary?",
  "What's the most memorable dream you've ever had?",
  "Have you ever accidentally sent a message to the wrong group chat?",
  "What's the most embarrassing thing you've done on a video call?",
  "Have you ever been caught singing or dancing when you thought you were alone?",
  "What's the most unusual place you've fallen asleep?",
  "Have you ever had a crush on a friend's sibling?",
  "What's the most memorable dream you've ever had?",
  "Have you ever had a celebrity reply or react to your social media post?",
  "What's something you're secretly proud of but haven't told anyone?",
  "Have you ever borrowed something and never returned it?",
  "What's the most embarrassing thing your parents have caught you doing?",
  "Have you ever pretended to be interested in a hobby just to impress someone?",
  "What's the most ridiculous rumor you've heard about yourself?",
  "Have you ever had a disagreement with a teacher about something?",
  "What's a moment you felt proud of yourself recently?",
  "Have you ever had a crush on someone from a different school?",
  "What's a talent or skill you've always wanted to learn?",
  "Have you ever had a pet you were afraid of?",
  "What's something you've done that your parents still don't know about?",
  "Have you ever tried a food combination that turned out to be surprisingly good?",
  "What's the most memorable gift you've ever received?",
  "Have you ever accidentally insulted someone without realizing it?",
  "What's a book or movie you secretly enjoy even though it's considered 'uncool'?",
  "Have you ever prank-called someone you know?",
  "What's a goal you've set for yourself in the next year?",
  "Have you ever gotten lost in a place you thought you knew well?",
  "What's a place you'd love to travel to someday?",
  "Have you ever had an embarrassing wardrobe malfunction?",
  "What's a song you can't help but sing along to every time it plays?",
  "Have you ever experienced a strange phobia or fear?",
  "What's the most interesting fact you've learned recently?",
  "Have you ever had a crush on a character from a video game or anime?",
  "What's the most challenging assignment or project you've worked on?",
  "Have you ever accidentally sent a message about someone to the person you were talking about?",
  "What's a movie that made you cry or feel emotional?",
  "Have you ever tried a beauty or fashion trend that you later regretted?",
  "What's the most unusual place you've visited on a family vacation?",
  "Have you ever gotten into an argument with a friend over something trivial?",
  "What's a hobby or activity you enjoy that most people your age might find boring?",
  "Have you ever had a crush on a fictional character from a book or TV show?",
  "What's a moment you felt truly confident and empowered?",
  "Have you ever had a disagreement with a friend that lasted a while?",
  "What's a skill you possess that you think is underrated?",
  "Have you ever accidentally liked an old post while stalking someone on social media?",
  "Have you ever had a funny or embarrassing encounter with a teacher outside of school?",
  "What's the most creative excuse you've come up with to get out of a social event?",
  "Have you ever had a crush on someone you met while on vacation?",
  "What's the most valuable lesson you've learned from a mistake you made?",
  "Have you ever had a secret talent that surprised your friends when you revealed it?",
  "What's a habit or routine you have that you think is unique or quirky?",
  "Have you ever had a memorable encounter with a stranger that left an impression on you?",
  "What's something you've accomplished that you're really proud of?",
  "Have you ever had an embarrassing encounter with technology (like accidentally calling someone, sending the wrong message, etc.)?",
  "What's the most exciting thing you've ever won or earned as a prize?",
  "Have you ever had a crush on someone from a different country or culture?",
  "What's a question you've always wanted to ask your parents but never have?",
  "Have you ever had a moment where you felt like you were in a movie or a book?",
  "What's the most outrageous outfit you've worn for a theme party or event?",
  "Have you ever tried a new food that you were initially hesitant about but ended up loving?",
  "What's the most memorable adventure you've had with your friends?",
  "Have you ever made a big decision based on a gut feeling or intuition?",
  "What's something you've learned recently that you think is fascinating?",
  "Have you ever had a crush on someone you met through online gaming or a virtual platform?",
  "What's the most creative way you've ever solved a problem?",
  "Have you ever had a funny or embarrassing moment during a school presentation?",
  "What's the most random act of kindness you've ever witnessed or performed?",
  "Have you ever had a dream that felt so real you couldn't tell if it actually happened?",
  "What's a piece of advice you've received that has stuck with you?",
  "Have you ever had a disagreement with a sibling that turned into a funny story?",
  "What's the most unexpected friendship you've formed?",
  "Have you ever had a crush on someone who is significantly older or younger than you?",
  "What's the most interesting place you've explored in your hometown?",
  "Have you ever had a moment where you felt truly grateful and appreciative?",
  "What's something you've accomplished that you never thought you could do?",
  "Have you ever accidentally embarrassed yourself in front of a group of people?",
  "What's a movie or TV show you've watched multiple times and still enjoy?",
  "Have you ever had a funny or awkward encounter with a crush's parents?",
  "What's the most spontaneous adventure you've had with your friends?",
  "Have you ever had a crush on a friend's older sibling or younger sibling?",
  "What's a hobby or interest you've recently discovered and become passionate about?",
  "Have you ever had a crush on someone you met through a school club or extracurricular activity?",
  "What's a memorable inside joke or funny phrase that you and your friends share?",
  "Have you ever had an unexpected encounter with a wild animal?",
  "What's the most exciting event you're looking forward to in the near future?",
  "Have you ever experienced a 'small world' moment where you unexpectedly met someone you knew in an unexpected place?",
  "What's a decision you've made that you later realized was a mistake?",
  "Have you ever had a crush on someone you met at a family gathering or reunion?",
  "What's the most interesting or unique place you've ever been to on a school field trip?",
  "Have you ever had a moment where you felt like you were in a reality TV show?",
  "What's a cause or social issue that you're passionate about?",
  "Have you ever had an embarrassing encounter with a teacher outside of school?",
  "What's the most unusual food combination you've tried and liked?",
  "Have you ever had a crush on someone you met while volunteering or doing community service?",
  "What's a memorable experience you've had at a live event, concert, or performance?",
  "Have you ever had a funny or awkward encounter with a neighbor?",
  "What's the most interesting fact you've learned about a different culture?",
  "Have you ever had a crush on someone you met during a family vacation?",
  "What's a book that had a significant impact on you or changed your perspective?",
  "Have you ever had an encounter with a celebrity or someone famous?",
  "What's the most adventurous thing you've done while exploring nature?",
  "Have you ever had a crush on a friend's friend?",
  "What's the most hilarious or unexpected thing you've witnessed in a public place?",
  "Have you ever had a crush on a friend's friend?",
  "What's the most unexpected friendship you've formed?",
  "Have you ever had a crush on someone who is significantly older or younger than you?",
  "What's the most interesting place you've explored in your hometown?",
  "Have you ever had a moment where you felt truly grateful and appreciative?",
  "What's something you've accomplished that you never thought you could do?",
  "Have you ever accidentally embarrassed yourself in front of a group of people?",
  "What's a movie or TV show you've watched multiple times and still enjoy?",
  "Have you ever had a funny or awkward encounter with a crush's parents?",
  "What's the most spontaneous adventure you've had with your friends?",
  "Have you ever had a crush on a friend's older sibling or younger sibling?",
  "What's a hobby or interest you've recently discovered and become passionate about?",
  "Have you ever had a crush on someone you met through a school club or extracurricular activity?",
  "What's a memorable inside joke or funny phrase that you and your friends share?",
  "Have you ever had an unexpected encounter with a wild animal?",
  "What's the most exciting event you're looking forward to in the near future?",
  "Have you ever experienced a 'small world' moment where you unexpectedly met someone you knew in an unexpected place?",
  "What's a decision you've made that you later realized was a mistake?",
  "Have you ever had a crush on someone you met at a family gathering or reunion?",
  "What's the most interesting or unique place you've ever been to on a school field trip?",
  "Have you ever had a moment where you felt like you were in a reality TV show?",
  "What's a cause or social issue that you're passionate about?",
  "Have you ever had an embarrassing encounter with a teacher outside of school?",
  "What's the most unusual food combination you've tried and liked?",
  "Have you ever had a crush on someone you met while volunteering or doing community service?",
  "What's a memorable experience you've had at a live event, concert, or performance?",
  "Have you ever had a funny or awkward encounter with a neighbor?",
  "What's the most interesting fact you've learned about a different culture?",
  "Have you ever had a crush on someone you met during a family vacation?",
  "What's a book that had a significant impact on you or changed your perspective?",
  "Have you ever had an encounter with a celebrity or someone famous?",
  "What's the most adventurous thing you've done while exploring nature?",
  "Have you ever had a crush on a friend's friend?",
  "What's the most hilarious or unexpected thing you've witnessed in a public place?",
  "Have you ever tried a dare from a social media challenge?",
  "What's something you'd like to change about your school?",
  "Have you ever had a disagreement with a teacher?",
  "What's the most embarrassing thing you've posted on social media?",
  "Have you ever had a pet that you kept a secret from your parents?",
  "What's the most unusual pet you'd like to have?",
  "Have you ever pretended to like a certain type of music to fit in?",
  "What's the most embarrassing nickname you've been given?",
  "Have you ever had a crush on someone you met at a family event?",
  "What's a food you dislike that most people seem to enjoy?",
  "Have you ever accidentally sent a text to the wrong person?",
  "What's your favorite childhood memory?",
  "Have you ever eavesdropped on a conversation?",
  "What's the most creative excuse you've come up with to get out of something?",
  "Have you ever been grounded? What was it for?",
  "What's the most daring fashion choice you've made?",
  "Have you ever been on a blind date or set someone up on one?",
  "What's a TV show or movie you're embarrassed to admit you enjoy?",
  "Have you ever had a crush on someone you met at a family event?",
  "What's a skill you wish you were better at?",
  "Have you ever kept a journal or diary?",
  "What's the most memorable dream you've ever had?",
  "Have you ever accidentally sent a message to the wrong group chat?",
  "What's the most embarrassing thing you've done on a video call?",
  "Have you ever been caught singing or dancing when you thought you were alone?",
  "What's the most unusual place you've fallen asleep?",
  "Have you ever had a crush on a friend's sibling?",
  "What's the most memorable dream you've ever had?",
  "Have you ever had a celebrity reply or react to your social media post?",
  "What's something you're secretly proud of but haven't told anyone?",
  "Have you ever borrowed something and never returned it?",
  "What's the most embarrassing thing your parents have caught you doing?",
  "Have you ever pretended to be interested in a hobby just to impress someone?",
  "What's the most ridiculous rumor you've heard about yourself?",
  "Have you ever had a disagreement with a teacher about something?",
  "What's a moment you felt proud of yourself recently?",
  "Have you ever had a crush on someone from a different school?",
  "What's a talent or skill you've always wanted to learn?",
  "Have you ever had a pet you were afraid of?",
  "What's something you've done that your parents still don't know about?",
  "Have you ever tried a food combination that turned out to be surprisingly good?",
  "What's the most memorable gift you've ever received?",
  "Have you ever accidentally insulted someone without realizing it?",
  "What's a book or movie you secretly enjoy even though it's considered 'uncool'?",
  "Have you ever prank-called someone you know?",
  "What's a goal you've set for yourself in the next year?",
  "Have you ever gotten lost in a place you thought you knew well?",
  "What's a place you'd love to travel to someday?",
  "Have you ever had an embarrassing wardrobe malfunction?",
  "What's a song you can't help but sing along to every time it plays?",
  "Have you ever experienced a strange phobia or fear?",
  "What's the most interesting fact you've learned recently?",
  "Have you ever had a crush on a character from a video game or anime?",
  "What's the most challenging assignment or project you've worked on?",
  "Have you ever accidentally sent a message about someone to the person you were talking about?",
  "What's a movie that made you cry or feel emotional?",
  "Have you ever tried a beauty or fashion trend that you later regretted?",
  "What's the most unusual place you've visited on a family vacation?",
  "Have you ever gotten into an argument with a friend over something trivial?",
  "What's a hobby or activity you enjoy that most people your age might find boring?",
  "Have you ever had a crush on a fictional character from a book or TV show?",
  "What's a moment you felt truly confident and empowered?",
  "Have you ever had a disagreement with a friend that lasted a while?",
  "What's a skill you possess that you think is underrated?",
  "Have you ever accidentally liked an old post while stalking someone on social media?",
  "Have you ever had a funny or embarrassing encounter with a teacher outside of school?",
  "What's the most creative excuse you've come up with to get out of a social event?",
  "Have you ever had a crush on someone you met while on vacation?",
  "What's the most valuable lesson you've learned from a mistake you made?",
  "Have you ever had a secret talent that surprised your friends when you revealed it?",
  "What's a habit or routine you have that you think is unique or quirky?",
  "Have you ever had a memorable encounter with a stranger that left an impression on you?",
  "What's something you've accomplished that you're really proud of?",
  "Have you ever had an embarrassing encounter with technology (like accidentally calling someone, sending the wrong message, etc.)?",
  "What's the most exciting thing you've ever won or earned as a prize?",
  "Have you ever had a crush on someone from a different country or culture?",
  "What's a question you've always wanted to ask your parents but never have?",
  "Have you ever had a moment where you felt like you were in a movie or a book?",
  "What's the most outrageous outfit you've worn for a theme party or event?",
  "Have you ever tried a new food that you were initially hesitant about but ended up loving?",
  "What's the most memorable adventure you've had with your friends?",
  "Have you ever made a big decision based on a gut feeling or intuition?",
  "What's something you've learned recently that you think is fascinating?",
  "Have you ever had a crush on someone you met through online gaming or a virtual platform?",
  "What's the most creative way you've ever solved a problem?",
  "Have you ever had a funny or embarrassing moment during a school presentation?",
  "What's the most random act of kindness you've ever witnessed or performed?",
  "Have you ever had a dream that felt so real you couldn't tell if it actually happened?",
  "What's a piece of advice you've received that has stuck with you?",
  "Have you ever had a disagreement with a sibling that turned into a funny story?",
  "What's the most unexpected friendship you've formed?",
  "Have you ever had a crush on someone who is significantly older or younger than you?",
  "What's the most interesting place you've explored in your hometown?",
  "Have you ever had a moment where you felt truly grateful and appreciative?",
  "What's something you've accomplished that you never thought you could do?",
  "Have you ever accidentally embarrassed yourself in front of a group of people?",
  "What's a movie or TV show you've watched multiple times and still enjoy?",
  "Have you ever had a funny or awkward encounter with a crush's parents?",
  "What's the most spontaneous adventure you've had with your friends?",
  "Have you ever had a crush on a friend's older sibling or younger sibling?",
  "What's a hobby or interest you've recently discovered and become passionate about?",
  "Have you ever had a crush on someone you met through a school club or extracurricular activity?",
  "What's a memorable inside joke or funny phrase that you and your friends share?",
  "Have you ever had an unexpected encounter with a wild animal?",
  "What's the most exciting event you're looking forward to in the near future?",
  "Have you ever experienced a 'small world' moment where you unexpectedly met someone you knew in an unexpected place?",
  "What's a decision you've made that you later realized was a mistake?",
  "Have you ever had a crush on someone you met at a family gathering or reunion?",
  "What's the most interesting or unique place you've ever been to on a school field trip?",
  "Have you ever had a moment where you felt like you were in a reality TV show?",
  "What's a cause or social issue that you're passionate about?",
  "Have you ever had an embarrassing encounter with a teacher outside of school?",
  "What's the most unusual food combination you've tried and liked?",
  "Have you ever had a crush on someone you met while volunteering or doing community service?",
  "What's a memorable experience you've had at a live event, concert, or performance?",
  "Have you ever had a funny or awkward encounter with a neighbor?",
  "What's the most interesting fact you've learned about a different culture?",
  "Have you ever had a crush on someone you met during a family vacation?",
  "What's a book that had a significant impact on you or changed your perspective?",
  "Have you ever had an encounter with a celebrity or someone famous?",
  "What's the most adventurous thing you've done while exploring nature?",
  "Have you ever had a crush on a friend's friend?",
  "What's the most hilarious or unexpected thing you've witnessed in a public place?",
  "Have you ever tried a dare from a social media challenge?",
  "What's something you'd like to change about your school?",
  "Have you ever had a disagreement with a teacher?",
  "What's the most embarrassing thing you've posted on social media?",
  "Have you ever had a pet that you kept a secret from your parents?",
  "What's the most unusual pet you'd like to have?",
  "Have you ever pretended to like a certain type of music to fit in?",
  "What's the most embarrassing nickname you've been given?",
  "Have you ever had a crush on someone you met at a family event?",
  "What's a food you dislike that most people seem to enjoy?",
  "Have you ever accidentally sent a text to the wrong person?",
  "What's your favorite childhood memory?",
  "Have you ever eavesdropped on a conversation?",
  "What's the most creative excuse you've come up with to get out of something?",
  "Have you ever been grounded? What was it for?",
  "What's the most daring fashion choice you've made?",
  "Have you ever been on a blind date or set someone up on one?",
  "What's a TV show or movie you're embarrassed to admit you enjoy?",
  "Have you ever had a crush on someone you met at a family event?",
  "What's a skill you wish you were better at?",
  "Have you ever kept a journal or diary?",
  "What's the most memorable dream you've ever had?",
  "Have you ever accidentally sent a message to the wrong group chat?",
  "What's the most embarrassing thing you've done on a video call?",
  "Have you ever been caught singing or dancing when you thought you were alone?",
  "What's the most unusual place you've fallen asleep?",
  "Have you ever had a crush on a friend's sibling?",
  "What's the most memorable dream you've ever had?",
  "Have you ever had a celebrity reply or react to your social media post?",
  "What's something you're secretly proud of but haven't told anyone?",
  "Have you ever borrowed something and never returned it?",
  "What's the most embarrassing thing your parents have caught you doing?",
  "Have you ever pretended to be interested in a hobby just to impress someone?",
  "What's the most ridiculous rumor you've heard about yourself?",
  "Have you ever had a disagreement with a teacher about something?",
  "What's a moment you felt proud of yourself recently?",
  "Have you ever had a crush on someone from a different school?",
  "What's a talent or skill you've always wanted to learn?",
  "Have you ever had a pet you were afraid of?",
  "What's something you've done that your parents still don't know about?",
  "Have you ever tried a food combination that turned out to be surprisingly good?",
  "What's the most memorable gift you've ever received?",
  "Have you ever accidentally insulted someone without realizing it?",
  "What's a book or movie you secretly enjoy even though it's considered 'uncool'?",
  "Have you ever prank-called someone you know?",
  "What's a goal you've set for yourself in the next year?",
  "Have you ever gotten lost in a place you thought you knew well?",
  "What's a place you'd love to travel to someday?",
  "Have you ever had an embarrassing wardrobe malfunction?",
  "What's a song you can't help but sing along to every time it plays?",
  "Have you ever experienced a strange phobia or fear?",
  "What's the most interesting fact you've learned recently?",
  "Have you ever had a crush on a character from a video game or anime?",
  "What's the most challenging assignment or project you've worked on?",
  "Have you ever accidentally sent a message about someone to the person you were talking about?",
  "What's a movie that made you cry or feel emotional?",
  "Have you ever tried a beauty or fashion trend that you later regretted?",
  "What's the most unusual place you've visited on a family vacation?",
  "Have you ever gotten into an argument with a friend over something trivial?",
  "What's a hobby or activity you enjoy that most people your age might find boring?",
  "Have you ever had a crush on a fictional character from a book or TV show?",
  "What's a moment you felt truly confident and empowered?",
  "Have you ever had a disagreement with a friend that lasted a while?",
  "What's a skill you possess that you think is underrated?",
  "Have you ever accidentally liked an old post while stalking someone on social media?",
  "Have you ever had a funny or embarrassing encounter with a teacher outside of school?",
  "What's the most creative excuse you've come up with to get out of a social event?",
  "Have you ever had a crush on someone you met while on vacation?",
  "What's the most valuable lesson you've learned from a mistake you made?",
  "Have you ever had a secret talent that surprised your friends when you revealed it?",
  "What's a habit or routine you have that you think is unique or quirky?",
  "Have you ever had a memorable encounter with a stranger that left an impression on you?",
  "What's something you've accomplished that you're really proud of?",
  "Have you ever had an embarrassing encounter with technology (like accidentally calling someone, sending the wrong message, etc.)?",
  "What's the most exciting thing you've ever won or earned as a prize?",
  "Have you ever had a crush on someone from a different country or culture?",
  "What's a question you've always wanted to ask your parents but never have?",
  "Have you ever had a moment where you felt like you were in a movie or a book?",
  "What's the most outrageous outfit you've worn for a theme party or event?",
  "Have you ever tried a new food that you were initially hesitant about but ended up loving?",
  "What's the most memorable adventure you've had with your friends?",
  "Have you ever made a big decision based on a gut feeling or intuition?",
  "What's something you've learned recently that you think is fascinating?",
  "Have you ever had a crush on someone you met through online gaming or a virtual platform?",
  "What's the most creative way you've ever solved a problem?",
  "Have you ever had a funny or embarrassing moment during a school presentation?",
  "What's the most random act of kindness you've ever witnessed or performed?",
  "Have you ever had a dream that felt so real you couldn't tell if it actually happened?",
  "What's a piece of advice you've received that has stuck with you?",
  "Have you ever had a disagreement with a sibling that turned into a funny story?",
  "What's the most unexpected friendship you've formed?",
  "Have you ever had a crush on someone who is significantly older or younger than you?",
  "What's the most interesting place you've explored in your hometown?",
  "Have you ever had a moment where you felt truly grateful and appreciative?",
  "What's something you've accomplished that you never thought you could do?",
  "Have you ever accidentally embarrassed yourself in front of a group of people?",
  "What's a movie or TV show you've watched multiple times and still enjoy?",
  "Have you ever had a funny or awkward encounter with a crush's parents?",
  "What's the most spontaneous adventure you've had with your friends?",
  "Have you ever had a crush on a friend's older sibling or younger sibling?",
  "What's a hobby or interest you've recently discovered and become passionate about?",
  "Have you ever had a crush on someone you met through a school club or extracurricular activity?",
  "What's a memorable inside joke or funny phrase that you and your friends share?",
  "Have you ever had an unexpected encounter with a wild animal?",
  "What's the most exciting event you're looking forward to in the near future?",
  "Have you ever experienced a 'small world' moment where you unexpectedly met someone you knew in an unexpected place?",
  "What's a decision you've made that you later realized was a mistake?",
  "Have you ever had a crush on someone you met at a family gathering or reunion?",
  "What's the most interesting or unique place you've ever been to on a school field trip?",
  "Have you ever had a moment where you felt like you were in a reality TV show?",
  "What's a cause or social issue that you're passionate about?",
  "Have you ever had an embarrassing encounter with a teacher outside of school?",
  "What's the most unusual food combination you've tried and liked?",
  "Have you ever had a crush on someone you met while volunteering or doing community service?",
  "What's a memorable experience you've had at a live event, concert, or performance?",
  "Have you ever had a funny or awkward encounter with a neighbor?",
  "What's the most interesting fact you've learned about a different culture?",
  "Have you ever had a crush on someone you met during a family vacation?",
  "What's a book that had a significant impact on you or changed your perspective?",
  "Have you ever had an encounter with a celebrity or someone famous?",
  "What's the most adventurous thing you've done while exploring nature?",
  "Have you ever had a crush on a friend's friend?",
  "What's the most hilarious or unexpected thing you've witnessed in a public place?",
  "Have you ever tried a dare from a social media challenge?",
  "What's something you'd like to change about your school?",
  "Have you ever had a disagreement with a teacher?",
  "What's the most embarrassing thing you've posted on social media?",
  "Have you ever had a pet that you kept a secret from your parents?",
  "What's the most unusual pet you'd like to have?",
  "Have you ever pretended to like a certain type of music to fit in?",
  "What's the most embarrassing nickname you've been given?",
  "Have you ever had a crush on someone you met at a family event?",
  "What's a food you dislike that most people seem to enjoy?",
  "Have you ever accidentally sent a text to the wrong person?",
  "What's your favorite childhood memory?",
  "Have you ever eavesdropped on a conversation?",
  "What's the most creative excuse you've come up with to get out of something?",
  "Have you ever been grounded? What was it for?",
  "What's the most daring fashion choice you've made?",
  "Have you ever been on a blind date or set someone up on one?",
  "What's a TV show or movie you're embarrassed to admit you enjoy?",
  "Have you ever had a crush on someone you met at a family event?",
  "What's a skill you wish you were better at?",
  "Have you ever kept a journal or diary?",
  "What's the most memorable dream you've ever had?",
  "Have you ever accidentally sent a message to the wrong group chat?",
  "What's the most embarrassing thing you've done on a video call?",
  "Have you ever been caught singing or dancing when you thought you were alone?",
  "What's the most unusual place you've fallen asleep?",
  "Have you ever had a crush on a friend's sibling?",
  "What's the most memorable dream you've ever had?",
  "Have you ever had a celebrity reply or react to your social media post?",
  "What's something you're secretly proud of but haven't told anyone?",
  "Have you ever borrowed something and never returned it?",
  "What's the most embarrassing thing your parents have caught you doing?",
  "Have you ever pretended to be interested in a hobby just to impress someone?",
  "What's the most ridiculous rumor you've heard about yourself?",
  "Have you ever had a disagreement with a teacher about something?",
  "What's a moment you felt proud of yourself recently?",
  "Have you ever had a crush on someone from a different school?",
  "What's a talent or skill you've always wanted to learn?",
  "Have you ever had a pet you were afraid of?",
  "What's something you've done that your parents still don't know about?",
  "Have you ever tried a food combination that turned out to be surprisingly good?",
  "What's the most memorable gift you've ever received?",
  "Have you ever accidentally insulted someone without realizing it?",
  "What's a book or movie you secretly enjoy even though it's considered 'uncool'?",
  "Have you ever prank-called someone you know?",
  "What's a goal you've set for yourself in the next year?",
  "Have you ever gotten lost in a place you thought you knew well?",
  "What's a place you'd love to travel to someday?",
  "Have you ever had an embarrassing wardrobe malfunction?",
  "What's a song you can't help but sing along to every time it plays?",
  "Have you ever experienced a strange phobia or fear?",
  "What's the most interesting fact you've learned recently?",
  "Have you ever had a crush on a character from a video game or anime?",
  "What's the most challenging assignment or project you've worked on?",
  "Have you ever accidentally sent a message about someone to the person you were talking about?",
  "What's a movie that made you cry or feel emotional?",
  "Have you ever tried a beauty or fashion trend that you later regretted?",
  "What's the most unusual place you've visited on a family vacation?",
  "Have you ever gotten into an argument with a friend over something trivial?",
  "What's a hobby or activity you enjoy that most people your age might find boring?",
  "Have you ever had a crush on a fictional character from a book or TV show?",
  "What's a moment you felt truly confident and empowered?",
  "Have you ever had a disagreement with a friend that lasted a while?",
  "What's a skill you possess that you think is underrated?",
  "Have you ever accidentally liked an old post while stalking someone on social media?",
  "Have you ever had a funny or embarrassing encounter with a teacher outside of school?",
  "What's the most creative excuse you've come up with to get out of a social event?",
  "Have you ever had a crush on someone you met while on vacation?",
  "What's the most valuable lesson you've learned from a mistake you made?",
  "Have you ever had a secret talent that surprised your friends when you revealed it?",
  "What's a habit or routine you have that you think is unique or quirky?",
  "Have you ever had a memorable encounter with a stranger that left an impression on you?",
  "What's something you've accomplished that you're really proud of?",
  "Have you ever had an embarrassing encounter with technology (like accidentally calling someone, sending the wrong message, etc.)?",
  "What's the most exciting thing you've ever won or earned as a prize?",
  "Have you ever had a crush on someone from a different country or culture?",
  "What's a question you've always wanted to ask your parents but never have?",
  "Have you ever had a moment where you felt like you were in a movie or a book?",
  "What's the most outrageous outfit you've worn for a theme party or event?",
  "Have you ever tried a new food that you were initially hesitant about but ended up loving?",
  "What's the most memorable adventure you've had with your friends?",
  "Have you ever made a big decision based on a gut feeling or intuition?",
  "What's something you've learned recently that you think is fascinating?",
  "Have you ever had a crush on someone you met through online gaming or a virtual platform?",
  "What's the most creative way you've ever solved a problem?",
  "Have you ever had a funny or embarrassing moment during a school presentation?",
  "What's the most random act of kindness you've ever witnessed or performed?",
  "Have you ever had a dream that felt so real you couldn't tell if it actually happened?",
  "What's a piece of advice you've received that has stuck with you?",
  "Have you ever had a disagreement with a sibling that turned into a funny story?",
  "What's the most unexpected friendship you've formed?",
  "Have you ever had a crush on someone who is significantly older or younger than you?",
  "What's the most interesting place you've explored in your hometown?",
  "Have you ever had a moment where you felt truly grateful and appreciative?",
  "What's something you've accomplished that you never thought you could do?",
  "Have you ever accidentally embarrassed yourself in front of a group of people?",
  "What's a movie or TV show you've watched multiple times and still enjoy?",
  "Have you ever had a funny or awkward encounter with a crush's parents?",
  "What's the most spontaneous adventure you've had with your friends?",
  "Have you ever had a crush on a friend's older sibling or younger sibling?",
  "What's a hobby or interest you've recently discovered and become passionate about?",
  "Have you ever had a crush on someone you met through a school club or extracurricular activity?",
  "What's a memorable inside joke or funny phrase that you and your friends share?",
  "Have you ever had an unexpected encounter with a wild animal?",
  "What's the most exciting event you're looking forward to in the near future?",
  "Have you ever experienced a 'small world' moment where you unexpectedly met someone you knew in an unexpected place?",
  "What's a decision you've made that you later realized was a mistake?",
  "Have you ever had a crush on someone you met at a family gathering or reunion?",
  "What's the most interesting or unique place you've ever been to on a school field trip?",
  "Have you ever had a moment where you felt like you were in a reality TV show?",
  "What's a cause or social issue that you're passionate about?",
  "Have you ever had an embarrassing encounter with a teacher outside of school?",
  "What's the most unusual food combination you've tried and liked?",
  "Have you ever had a crush on someone you met while volunteering or doing community service?",
  "What's a memorable experience you've had at a live event, concert, or performance?",
  "Have you ever had a funny or awkward encounter with a neighbor?",
  "What's the most interesting fact you've learned about a different culture?",
  "Have you ever had a crush on someone you met during a family vacation?",
  "What's a book that had a significant impact on you or changed your perspective?",
  "Have you ever had an encounter with a celebrity or someone famous?",
  "What's the most adventurous thing you've done while exploring nature?",
  "Have you ever had a crush on a friend's friend?",
  "What's the most hilarious or unexpected thing you've witnessed in a public place?",
  "Have you ever tried a dare from a social media challenge?",
  "What's something you'd like to change about your school?",
  "Have you ever had a disagreement with a teacher?",
  "What's the most embarrassing thing you've posted on social media?",
  "Have you ever had a pet that you kept a secret from your parents?",
  "What's the most unusual pet you'd like to have?",
  "Have you ever pretended to like a certain type of music to fit in?",
  "What's the most embarrassing nickname you've been given?",
  "Have you ever had a crush on someone you met at a family event?",
  "What's a food you dislike that most people seem to enjoy?",
  "Have you ever accidentally sent a text to the wrong person?",
  "What's your favorite childhood memory?",
  "Have you ever eavesdropped on a conversation?",
  "What's the most creative excuse you've come up with to get out of something?",
  "Have you ever been grounded? What was it for?",
  "What's the most daring fashion choice you've made?",
  "Have you ever been on a blind date or set someone up on one?",
  "What's a TV show or movie you're embarrassed to admit you enjoy?",
  "Have you ever had a crush on someone you met at a family event?",
  "What's a skill you wish you were better at?",
  "Have you ever kept a journal or diary?",
  "What's the most memorable dream you've ever had?",
  "Have you ever accidentally sent a message to the wrong group chat?",
  "What's the most embarrassing thing you've done on a video call?",
  "Have you ever been caught singing or dancing when you thought you were alone?",
  "What's the most unusual place you've fallen asleep?",
  "Have you ever had a crush on a friend's sibling?",
  "What's the most memorable dream you've ever had?",
  "Have you ever had a celebrity reply or react to your social media post?",
  "What's something you're secretly proud of but haven't told anyone?",
  "Have you ever borrowed something and never returned it?",
  "What's the most embarrassing thing your parents have caught you doing?",
  "Have you ever pretended to be interested in a hobby just to impress someone?",
  "What's the most ridiculous rumor you've heard about yourself?",
  "Have you ever had a disagreement with a teacher about something?",
  "What's a moment you felt proud of yourself recently?",
  "Have you ever had a crush on someone from a different school?",
  "What's a talent or skill you've always wanted to learn?",
  "Have you ever had a pet you were afraid of?",
  "What's something you've done that your parents still don't know about?",
  "Have you ever tried a food combination that turned out to be surprisingly good?",
  "What's the most memorable gift you've ever received?",
  "Have you ever accidentally insulted someone without realizing it?",
  "What's a book or movie you secretly enjoy even though it's considered 'uncool'?",
  "Have you ever prank-called someone you know?",
  "What's a goal you've set for yourself in the next year?",
  "Have you ever gotten lost in a place you thought you knew well?",
  "What's a place you'd love to travel to someday?",
  "Have you ever had an embarrassing wardrobe malfunction?",
  "What's a song you can't help but sing along to every time it plays?",
  "Have you ever experienced a strange phobia or fear?",
  "What's the most interesting fact you've learned recently?",
  "Have you ever had a crush on a character from a video game or anime?",
  "What's the most challenging assignment or project you've worked on?",
  "Have you ever accidentally sent a message about someone to the person you were talking about?",
  "What's a movie that made you cry or feel emotional?",
  "Have you ever tried a beauty or fashion trend that you later regretted?",
  "What's the most unusual place you've visited on a family vacation?",
  "Have you ever gotten into an argument with a friend over something trivial?",
  "What's a hobby or activity you enjoy that most people your age might find boring?",
  "Have you ever had a crush on a fictional character from a book or TV show?",
  "What's a moment you felt truly confident and empowered?",
  "Have you ever had a disagreement with a friend that lasted a while?",
  "What's a skill you possess that you think is underrated?",
  "Have you ever accidentally liked an old post while stalking someone on social media?",
  "Have you ever had a funny or embarrassing encounter with a teacher outside of school?",
  "What's the most creative excuse you've come up with to get out of a social event?",
  "Have you ever had a crush on someone you met while on vacation?",
  "What's the most valuable lesson you've learned from a mistake you made?",
  "Have you ever had a secret talent that surprised your friends when you revealed it?",
  "What's a habit or routine you have that you think is unique or quirky?",
  "Have you ever had a memorable encounter with a stranger that left an impression on you?",
  "What's something you've accomplished that you're really proud of?",
  "Have you ever had an embarrassing encounter with technology (like accidentally calling someone, sending the wrong message, etc.)?",
  "What's the most exciting thing you've ever won or earned as a prize?",
  "Have you ever had a crush on someone from a different country or culture?",
  "What's a question you've always wanted to ask your parents but never have?",
  "Have you ever had a moment where you felt like you were in a movie or a book?",


    "Can you give directions to the closest grocery store?",
    "Have you been called a snitch?",
    "What is a bad habit that you have?",
    "Have you ever peeked at Christmas presents early?",
    "What is your favorite sport?",
    "When was the last time your room saw a vacuum?",
    "If you get hold of a time machine, ‘when’ would you like to go?",
    "What is the first thing you do after school?",
    "Is there anything hidden under your bed?",
    "Which would you rather have for dinner: fast food or Mom’s home cooking?",
    "Do you have a cell phone?",
    "When was the last time you sincerely apologized?",
    "Have you poured salt on a slug?",
    "What would be your new name if you were allowed to choose one?",
    "What do you like most about everyone in the room?",
    "Have you skipped school?",
    "Do you have hidden snacks in your room?",
    "Who is your favorite superhero?",
    "Have you ever cried during a movie? If so, which one?",
    "What’s the dumbest thing you ever said or did around a boy/girl you liked?",
    "Do you bite your nails?",
    "Would you rather be a princess/prince or a mermaid/man?",
    "Have you lied about your age?",
    "Which Harry Potter character would you like to be and why?",
    "Are you afraid of the dark?",
    "Have you ever said you finished your dinner when you didn’t?",
    "Have you smelled the inside of a seashell?",
    "What is one thing you would change about yourself?",
    "Have you peed in a pool?",
    "When was the last time your room was cleaned?",
    "Have you ever passed gas and blamed someone else?",
    "What is the most annoying thing on Earth for you?",
    "Have you ever stolen anything?",
    "If you had a genie, what 3 things would you wish for?",
    "Have you tried to forge your parent’s signature?",
    "Have you ever been to a zoo?",
    "If you could be any celebrity, who would you be and why?",
    "Do you have a strange collection?",
    "Do you prefer cookies or cake?",
    "What makes you happy?",
    "Have you ever kept a goldfish alive for more than a year?",
    "Who do you have a crush on?",
    "What is your favorite sleeping position?",
    "Who do you want to be when you grow up?",
    "Would you rather have a sibling or a pet?",
    "Have you held a tarantula?",
    "Have you ever watched Blues Clues?",
    "What is a secret you have?",
    "What is your favorite amusement park ride?"
    // Add more truth questions here
  ];
  return truthOptions[Math.floor(Math.random() * truthOptions.length)];
}



function getRandomDare() {
  const dareOptions = [
    "Call a local grocery store and ask if they have any square watermelons.",
    "Write and perform a short rap about your favorite food.",
    "Put on a blindfold and try to draw a self-portrait on a piece of paper.",
    "Call a friend and try to convince them that you've just won the lottery (be creative!).",
    "Take a selfie imitating your favorite emoji and share it with your group.",
    "Pretend you're a sports commentator and give a play-by-play of you doing a simple task.",
    "Call a family member and tell them you're practicing to be a professional animal impersonator.",
    "Wear your socks on your hands and try to eat a snack without using your hands.",
    "Write a short and funny poem about a talking vegetable and read it aloud to the group.",
    "Take a selfie while trying to balance a spoon on your nose.",
    "Call a local toy store and ask if they sell invisible toys.",
    "Share a funny anecdote from your school days with your friends.",
    "Put on a blindfold and try to put on a jacket or sweater within 60 seconds.",
    "Call a friend and challenge them to a tongue twister showdown.",
    "Pretend to be a stand-up comedian and tell a funny joke to the group.",
    "Take a selfie making your best 'surprised' face and send it to a family member.",
    "Call a local restaurant and ask if they have a 'unicorn-themed' menu.",
    "Wear a pair of mismatched shoes for the next three rounds of the game.",
    "Write a short story about a talking household object and share it with your friends.",
    "Call a friend and try to have a conversation using only animal noises.",
    "Call a friend and challenge them to a 30-second dance-off over the phone.",
    "Wear a funny mask and record a short video message for your best friend.",
    "Text a family member a random word and challenge them to use it in a sentence.",
    "Try to do a handstand against a wall for as long as you can.",
    "Call a local pet store and ask if they have any invisible fish for sale.",
    "Take a selfie with a random object from your living room and caption it with a joke.",
    "Put on a blindfold and attempt to draw a simple picture of a tree.",
    "Call a friend and have a conversation using only emojis.",
    "Try to balance a spoon on your nose for 30 seconds.",
    "Write a short story about a talking sock and share it with the group.",
    "Call a local library and ask if they have any books on 'How to Speak Dragon.'",
    "Share a funny childhood memory with the group.",
    "Put on a pair of sunglasses and strike a cool pose for a photo.",
    "Take a selfie imitating your favorite celebrity and share it with your friends.",
    "Call a family member and tell them you've decided to become a professional bubble blower.",
    "Pretend to be a news anchor and give a weather report for your bedroom.",
    "Put on a blindfold and try to apply lipstick without a mirror.",
    "Call a friend and tell them a made-up joke, and see if you can make them laugh.",
    "Take a selfie while trying to touch your nose with your tongue.",
    "Create a short TikTok-style dance and perform it for your friends.",
    "Put on a blindfold and try to put on a pair of socks within 30 seconds.",
    "Call a local bakery and ask if they have any square donuts.",
    "Write and perform a 30-second commercial for a made-up product.",
    "Take a selfie with a random item from your bathroom and share it with the group.",
    "Call a friend and recite a tongue twister as fast as you can without stumbling.",
    "Wear a funny hat and introduce yourself to a neighbor you've never met.",
    "Attempt to do the moonwalk dance move for at least 20 seconds.",
    "Call a family member and tell them you're starting a collection of invisible art.",
    "Put on a blindfold and try to guess the scent of different candles.",
    "Text a friend a picture of your most 'dramatic' pose and ask them to rate it out of 10.",
    "Call a local pizza place and ask if they have a 'pizza-flavored pizza.'",
    "Share a short, funny story about a time you had a wardrobe malfunction.",
    "Put on a silly costume or outfit and take a walk around your neighborhood.",
    "Write a short poem about your favorite emoji and share it with the group.",
    "Call a friend and try to hold a conversation using only animal noises.",
    "Use your elbow to text a family member a random sentence and see if they can decipher it.",
    "Put on a blindfold and try to make a sandwich without looking.",
    "Call a local coffee shop and ask if they offer unicorn lattes.",
    "Take a selfie imitating a famous work of art and share it with your friends.",
    "Pretend to be a tour guide and give a virtual tour of your bedroom to the group.",
    "Put on a pair of gloves and try to peel a banana as gracefully as possible.",
    "Call a local pet store and inquire about buying a pet rock.",
    "Take a selfie with the most serious and dramatic expression you can make.",
    "Pretend you're a news reporter and give a breaking news report about an everyday object.",
    "Call a friend and have a conversation using only song lyrics.",
    "Put on a blindfold and try to guess the flavor of different types of chips.",
    "Go outside and do your best impression of your favorite animal for 30 seconds.",
    "Text your crush and ask them to suggest a fun activity to do together.",
    "Try to lick your elbow and record your attempt for the group.",
    "Call a local bookstore and ask if they have a section on 'How to Speak Unicorn.'",
    "Write a short poem about your favorite food and share it with the group.",
    "Wear your shoes on the wrong feet for the next three rounds of the game.",
    "Pretend to be a robot and communicate only in beeps and boops for the next five minutes.",
    "Call a family member and ask them for their best joke.",
    "Put a piece of chocolate on your forehead and try to eat it without using your hands.",
    "Take a funny selfie with a random object from your kitchen and send it to a friend.",
    "Put on a blindfold and attempt to draw a cat while your friends guide your hand.",
    "Call a friend and give them a 60-second pep talk as if they're about to run a marathon.",
    "Use a random household item as a microphone and give a speech about your favorite hobby.",
    "Take a selfie making a surprised face and share it with a random contact in your phone.",
    "Create a short rap about a random household item and perform it for the group.",
    "Wear oven mitts on your hands for the next three rounds of the game.",
    "Call a local store and ask if they have any invisible ink for sale.",
    "Put a piece of candy in your mouth and try to whistle your favorite tune.",
    "Send a selfie with a caption that says, 'I woke up like this!' to a friend.",
    "Write a funny and fictional story about a talking vegetable and share it with the group.",
    "Put on a random item of clothing inside-out and wear it that way for the next round.",
    "Call a local pizzeria and ask if they can make a pizza with only one topping in the shape of a smiley face.",
    "Use a hairbrush as a microphone and give a dramatic speech about your favorite food.",
    "Take a selfie with a random object from your room and caption it with a pun.",
    "Put a piece of tape on your nose and wear it like a makeshift mustache for the next hour.",
    "Send a text to a friend saying you've decided to become a professional tap dancer and need their support.",
    "Wear a silly disguise (hat, glasses, etc.) and take a walk around your block.",
    "Call a friend and try to have a conversation using only movie quotes.",
    "Go to your neighbor's house and ask if you can borrow a random item (toothbrush, banana, etc.).",
    "Sing the chorus of your favorite song in the loudest voice possible, right now!",
    "Call a friend and have a five-minute conversation using only animal sounds.",
    "Wear socks on your hands for the next three rounds of the game.",
    "Text your crush and tell them you just found a four-leaf clover and your luck is about to change.",
    "Put an ice cube down your back and keep it there until it melts.",
    "Attempt to hula hoop for one minute, even if you're not very good at it.",
    "Do a silly dance in the middle of a crowded area (with permission and while maintaining safety).",
    "Put a spoonful of peanut butter on your nose and try to lick it off.",
    "Call a local restaurant and ask if they have any 'unicorn specials' on the menu.",
    "Send a random friend a compliment and tell them you appreciate their friendship.",
    "Wear a funny hat for the next three rounds of the game.",
    "Walk outside and do your best impression of a celebrity while pretending you're being interviewed.",
    "Try to juggle three different fruits (or any safe objects) for one minute.",
    "Text a family member a made-up fact and see if they believe it.",
    "Balance a spoon on your nose and keep it there for as long as possible.",
    "Go to your fridge and create a 'sandwich' using the first three items you see (even if they don't go together).",
    "Call a friend and pretend you're a radio DJ announcing their favorite song is playing next.",
    "Put on a blindfold and let another player give you a makeover with items from around the room.",
    "Take a selfie with the goofiest expression and send it to the group chat.",
    "Take a selfie with the silliest face you can make and share it on your social media.",
    "Do your best dance moves to a popular song in a public place.",
    "Text your crush and tell them you have a secret you want to share (make up a harmless secret!).",
    "Wear your shirt inside out for the next hour.",
    "Call a random contact in your phone and sing 'Happy Birthday' to them, no matter the actual date.",
    "Put on a blindfold and try to do a trust fall with a friend.",
    "Send a message to a family member saying you're adopting a pet penguin and need their approval.",
    "Eat a spoonful of a condiment you wouldn't normally eat on its own (ketchup, mustard, mayo, etc.).",
    "Put an ice cube down your back and keep it there for 30 seconds.",
    "Try to juggle three random objects for one minute (make sure they're safe to juggle!).",
  
    "Stack five cookies on your forehead!",
    "After everything you say, add 'Whoa … I’m good!' for the next 15 minutes!",
    "Wear clean underwear on your head for the rest of the game!",
    "Spin 10 times and try to do hopscotch!",
    "Close your eyes every time someone talks to you!",
    "Get wrapped from head to toe in toilet paper!",
    "If it’s dark outside, leave the house and howl at the moon!",
    "Stand absolutely still for one minute!",
    "Go ask the neighbor for a cup of sugar!",
    "You can only speak to the tune of happy birthday for the next 30 minutes!",
    "Gently blow in the ear of the person to your left!",
    "Pop a balloon without using your hands or teeth!",
    "Eat a teaspoon of sugar and salt mixed together!",
    "Make up a poem out loud!",
    "Wink at the end of each sentence!",
    "Start every sentence with 'what is…'!",
    "Put ice cubes down your shirt, with the shirt tucked in!",
    "Wrap yourself in toilet paper!",
    "Play tag on all fours with your eyes closed until you tag someone!",
    "Make out with your hand!",
    "Build a tower taller than you out of anything you can!",
    "Ask the person on your left to make up a dare for you!",
    "Attempt to slip on a banana peel!",
    "Sing the ABCs backward!",
    "Go outside and yell, 'I believe in fairies!' loudly three times while clapping your hands as fast as you can!",
    "Fold a piece of paper with one hand!",
    "Talk while holding your tongue with your index finger and thumb!",
    "Paint your toenails with a crayon!",
    "Juggle eggs!",
    "Pretend to be T-Rex!",
    "Use a hairbrush as a microphone!",
    "Play fetch like a dog, running on all fours and using only your mouth to fetch!",
    "Disco dance!",
    "Tie your shoes together, and try not to forget!",
    "Stick round labels all over yourself and pretend to have chickenpox!",
    "Sing 'Un Poco Loco'!",
    "Spin around 10 times and try to walk a straight line!",
    "Skip instead of walking or running!",
    "Run around wearing socks on your hands, pants for a shirt, and a shirt for pants, for 3 minutes!",
    "Eat a pudding cup without using your hands!",
    "Wear underwear on your head for the rest of the game!",
    "Stuff as many marshmallows in your mouth as possible!",
    "Let the person next to you do your make-up any way they’d like!",
    "Say the alphabet backward as fast as you can!",
    "Touch your nose with your tongue!",
    "Chug a cup of milk, water, juice, etc.!",
    "Talk and act like a robot!",
    "Blindfold yourself for your next 3 turns!",
    "Ask someone to tango!",
    "Act like a gorilla and pretend to pick bugs out of your friend’s hair!",
    "Do the cha-cha until it is your turn again!",
    "Make animal sounds for a minute straight!"

    // Add more dare challenges here
  ];
  return dareOptions[Math.floor(Math.random() * dareOptions.length)];
}




updateResult();



